# Generated by Django 5.1.6 on 2025-05-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merch", "0002_shippinginfo_checkoutsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ProductVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=255)),
                ("sizes", models.ManyToManyField(to="merch.productsize")),
            ],
        ),
        migrations.DeleteModel(
            name="UserPayment",
        ),
    ]
