# Generated by Django 5.1.6 on 2025-03-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('show_location', models.CharField(default='TBD', max_length=75)),
                ('show_date', models.DateField()),
                ('doors_open', models.TimeField()),
                ('flyer', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
    ]
