# Generated by Django 5.1.6 on 2025-04-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberPhoto', models.ImageField(blank=True, upload_to='')),
                ('name', models.TextField()),
                ('bio', models.CharField(max_length=1000)),
            ],
        ),
    ]
