# Generated by Django 5.1.6 on 2025-04-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberPhoto',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
